server:
  port: 8200

spring:
  data:
    mongodb:
      database: geodb
      host: localhost

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
#  ssl:
#    key-store: keystore.p12
#    key-store-password: Qwerty
#    keyStoreType: PKCS12
#    keyAlias: tomcat